export class BeneficiaryModel {
    tx_external_code: string;
    tx_zone:string;
    id_department:string;
    id_province:string;
    id_district:string;
    id_ccpp:string;
    tx_annex:string;
    tx_east_wgs84: string;
    tx_north_wgs84: string;
    tx_east_psad56:string;
    tx_north_psad56:string;
    tx_zone_utm:string;
    tx_long_wgs84:string;
    tx_lat_wgs84:string;
    tx_long_psad56:string;
    tx_lat_psad56: string;
    tx_first_last_name: string;
    tx_second_last_name:string;
    tx_names:string;
    tx_document_number:string;
    tx_status:string;
    tx_distributor:string;
    tx_region:string;
    tx_region2:string;
    tx_rer:string;
    tx_data1:string;
    tx_data2: string;
    tx_data3: string;
    tx_ie:string;
    tx_ie_address:string;
    tx_month_block:string;
    tx_block:string;
    tx_type_document:string;
    tx_n_type_document: string;
    tx_serie: string;
    tx_number:string;
    int_period:number;
    tx_upf:string;
}